### ISSUE TITLE
`gettimeofday` should respect caller context

### ISSUE THREAD

**Issue by vanHoesel** [mjemmeson/Test-Time-HiRes#2]
According to the documentation: [Time::HiRess `gettimeofday`](https://metacpan.org/pod/Time::HiRes#gettimeofday-()) considers list and scalar context.

Current tests only return a list, but when done in scalar context, one only ends up with the number of microseconds. It should return the float.

Greets from an old friend!

**Comment by mjemmeson** [comment]
Hi Theo,

Good to hear from you and hope you are well!
Many thanks for this, I will be releasing a fixed version shortly.

Michael

**Comment by vanHoesel** [comment]
Awesome!!
