### ISSUE TITLE
`time` should return a number

### ISSUE THREAD

**Issue by vanHoesel** [mjemmeson/Test-Time-HiRes#3]
When calling the original [Time::HiRess time](https://metacpan.org/pod/Time::HiRes#time-()), it just returns a float like `1588931340.5056`.

The provided `time` mocked function returns a 'six digit padded' string.

This will cause even the simplest test to fail:

```perl
use Test::More;
use Test::Time::HiRes time => 256.875;

is time, 256.875;
```

suggested solution: `+0`

**Comment by mjemmeson** [comment]
Hi Theo,

Good to hear from you and hope you are well!
Many thanks for this, this is a really stupid error of mine! I will be releasing a fixed version shortly.

Michael
